spring:
  datasource:
    url: jdbc:h2:mem:test-bankdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: PUBLIC
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: test

h2:
  tcp:
    enabled: false

external:
  logging:
    url: https://httpstat.us/200

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

app:
  jwt:
    secret: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"
    expiration-ms: 3600000

